; Private nRF52840 + STM32WL bridge + ST7789 240x240 board
[env:nrf52840_sx1262_st7789]
custom_meshtastic_hw_model = 255
custom_meshtastic_hw_model_slug = PRIVATE_HW_NRF52840_STM32WL_ST7789
custom_meshtastic_architecture = nrf52840
custom_meshtastic_actively_supported = false
custom_meshtastic_support_level = 3
custom_meshtastic_display_name = Private nRF52840 STM32WL Bridge ST7789
custom_meshtastic_tags = DIY, Private

extends = nrf52840_base
board = promicro-nrf52840
board_level = extra
debug_tool = jlink

build_flags = ${nrf52840_sx1262_st7789_common.build_flags}
  -D RIPU_RADIO_SPI_FREQUENCY=250000

build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/diy/nrf52840_sx1262_st7789>

lib_deps =
  ${nrf52840_base.lib_deps}

lib_ignore =
  ESP8266 and ESP32 TFT driver for st7789 displays

[nrf52840_sx1262_st7789_common]
build_flags = ${nrf52840_base.build_flags}
  -I variants/nrf52840/diy/nrf52840_sx1262_st7789
  -D PRIVATE_HW
  -D NRF52840_STM32WL_ST7789
  -D SPI_32MHZ_INTERFACE=1
  -D CONFIG_NFCT_PINS_AS_GPIOS=1
  -D MESHTASTIC_EXCLUDE_GPS=1
